version: '2'

services:
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:$PORT
        --access-logfile -
        --reload
        "notepad.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/notepad'
    ports:
      - "8000:8000"
